# Copyright (c) 2011-2018 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
# Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG.

apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-tool
spec:
  template:
    metadata:
      name: cluster-tool
    spec:
      containers:
      - name: cluster-tool
        image: store/softwareag/terracotta-cluster-tool:10.2
        args: ["configure", "-n", "MyCluster", "/configs/stripe1.xml", "/configs/stripe2.xml"]
        env:
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
        - name: config-volume
          mountPath: /configs
        - name: license-volume
          mountPath: /licenses
      volumes:
      - name: config-volume
        configMap:
          name: tc-configs
      - name: license-volume
        configMap:
          name: license
      restartPolicy: OnFailure

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: store-client
  name: store-client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: store-client
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - clientnodes
      containers:
      - image: store/softwareag/sample-tcstore-client:10.2
        name: store-client
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: TERRACOTTA_SERVER_URL
          value: "terracotta-1-1:9410,terracotta-1-2:9410,terracotta-2-1:9410,terracotta-2-2:9410"
        - name: NUMBER_OF_RECORDS
          value: "1500000"
        - name: POUNDING_INTERVAL_MS
          value: "100"
        - name: ENTRY_VALUES_MEAN_SIZE_KB
          value: "25"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: caching-client
  name: caching-client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: caching-client
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - clientnodes
      containers:
      - image: store/softwareag/sample-ehcache-client:10.2
        name: caching-client
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: TERRACOTTA_SERVER_URL
          value: "terracotta-1-1:9410,terracotta-1-2:9410,terracotta-2-1:9410,terracotta-2-2:9410"
        - name: CLUSTERED_DEDICATED_SIZE
          value: "5"
        - name: CLUSTERED_DEDICATED_SIZE_UNIT
          value: "GB"
        - name: RESOURCE_POOL_SIZE
          value: "10"
        - name: RESOURCE_POOL_SIZE_UNIT
          value: "GB"
        - name: ENTRY_KEYS_SPREAD
          value: "50000"
        - name: POUNDING_INTERVAL_MS
          value: "1000"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tmc
  name: tmc-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tmc
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - clientnodes
      containers:
      - image: store/softwareag/tmc:10.2
        name: tmc
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: TMS_DEFAULTURL
          value: "terracotta://terracotta-1-1:9410,terracotta-1-2:9410,terracotta-2-1:9410,terracotta-2-2:9410"
#        - name: JAVA_OPTS
#          value: "-Dlogging.level.com.terracottatech.management=TRACE"
        ports:
        - containerPort: 9480
        volumeMounts:
        - name: tmcdata
          mountPath: /data/tmc/
      volumes:
      - name: tmcdata
        persistentVolumeClaim:
          claimName: tmcdata
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: tmc
  labels:
    app: tmc
spec:
  ports:
  - name: tmc-port
    port: 9480
  type: LoadBalancer
  selector:
    app: tmc

---

apiVersion: v1
kind: Service
metadata:
  name: terracotta-1-1
  labels:
    app: terracotta-1-1
spec:
  type: ClusterIP
  ports:
  - port: 9410
    name: terracotta-port
    targetPort: terracotta-port
    protocol: TCP
  - port: 9430
    name: sync-port
    targetPort: sync-port
    protocol: TCP
  selector:
    app: terracotta-1-1

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: terracotta-1-1
  name: terracotta-1-1-deployment
spec:
  # replica set definition
  replicas: 1
  template:
    metadata:
      labels:
        app: terracotta-1-1
        app-role: terracotta-server
    spec:
      hostname: terracotta-1-1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app-role
                operator: In
                values:
                - terracotta-server
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - nodes
      # pod definition
      containers:
      - name: terracotta
        image: store/softwareag/terracotta-server:10.2
        command: ["bin/start-tc-server.sh"]
        args: ["-f", "/configs/stripe1.xml", "-n", "terracotta-1-1"]
        ports:
        - containerPort: 9410
          name: terracotta-port
        - containerPort: 9430
          name: sync-port
        env:
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
        - name: dataroots-1-1
          mountPath: /data/dataroots
#        - name: backups
#          mountPath: /data/backups
        - name: config-volume
          mountPath: /configs
      volumes:
        - name: config-volume
          configMap:
            name: tc-configs
        - name: dataroots-1-1
          persistentVolumeClaim:
            claimName: dataroots-1-1
#        - name: backups
#          persistentVolumeClaim:
#            claimName: backups-volume-claim

---

apiVersion: v1
kind: Service
metadata:
  name: terracotta-1-2
  labels:
    app: terracotta-1-2
spec:
  type: ClusterIP
  ports:
  - port: 9410
    name: terracotta-port
    targetPort: terracotta-port
    protocol: TCP
  - port: 9430
    name: sync-port
    targetPort: sync-port
    protocol: TCP
  selector:
    app: terracotta-1-2

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: terracotta-1-2
  name: terracotta-1-2-deployment
spec:
  # replica set definition
  replicas: 1
  template:
    metadata:
      labels:
        app: terracotta-1-2
        app-role: terracotta-server
    spec:
      hostname: terracotta-1-2
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app-role
                operator: In
                values:
                - terracotta-server
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - nodes
      # pod definition
      containers:
      - name: terracotta
        image: store/softwareag/terracotta-server:10.2
        command: ["bin/start-tc-server.sh"]
        args: ["-f", "/configs/stripe1.xml", "-n", "terracotta-1-2"]
        ports:
        - containerPort: 9410
          name: terracotta-port
        - containerPort: 9430
          name: sync-port
        env:
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
        - name: dataroots-1-2
          mountPath: /data/dataroots
#        - name: backups
#          mountPath: /data/backups
        - name: config-volume
          mountPath: /configs
      volumes:
        - name: config-volume
          configMap:
            name: tc-configs
        - name: dataroots-1-2
          persistentVolumeClaim:
            claimName: dataroots-1-2
#        - name: backups
#          persistentVolumeClaim:
#            claimName: backups-volume-claim

---

apiVersion: v1
kind: Service
metadata:
  name: terracotta-2-1
  labels:
    app: terracotta-2-1
spec:
  type: ClusterIP
  ports:
  - port: 9410
    name: terracotta-port
    targetPort: terracotta-port
    protocol: TCP
  - port: 9430
    name: sync-port
    targetPort: sync-port
    protocol: TCP
  selector:
    app: terracotta-2-1

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: terracotta-2-1
  name: terracotta-2-1-deployment
spec:
  # replica set definition
  replicas: 1
  template:
    metadata:
      labels:
        app: terracotta-2-1
        app-role: terracotta-server
    spec:
      hostname: terracotta-2-1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app-role
                operator: In
                values:
                - terracotta-server
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - nodes
      # pod definition
      containers:
      - name: terracotta
        image: store/softwareag/terracotta-server:10.2
        command: ["bin/start-tc-server.sh"]
        args: ["-f", "/configs/stripe2.xml", "-n", "terracotta-2-1"]
        ports:
        - containerPort: 9410
          name: terracotta-port
        - containerPort: 9430
          name: sync-port
        env:
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
        - name: dataroots-2-1
          mountPath: /data/dataroots
#        - name: backups
#          mountPath: /data/backups
        - name: config-volume
          mountPath: /configs
      volumes:
        - name: config-volume
          configMap:
            name: tc-configs
        - name: dataroots-2-1
          persistentVolumeClaim:
            claimName: dataroots-2-1
#        - name: backups
#          persistentVolumeClaim:
#            claimName: backups-volume-claim

---

apiVersion: v1
kind: Service
metadata:
  name: terracotta-2-2
  labels:
    app: terracotta-2-2
spec:
  type: ClusterIP
  ports:
  - port: 9410
    name: terracotta-port
    targetPort: terracotta-port
    protocol: TCP
  - port: 9430
    name: sync-port
    targetPort: sync-port
    protocol: TCP
  selector:
    app: terracotta-2-2

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: terracotta-2-2
  name: terracotta-2-2-deployment
spec:
  # replica set definition
  replicas: 1
  template:
    metadata:
      labels:
        app: terracotta-2-2
        app-role: terracotta-server
    spec:
      hostname: terracotta-2-2
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app-role
                operator: In
                values:
                - terracotta-server
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - nodes
      # pod definition
      containers:
      - name: terracotta
        image: store/softwareag/terracotta-server:10.2
        command: ["bin/start-tc-server.sh"]
        args: ["-f", "/configs/stripe2.xml", "-n", "terracotta-2-2"]
        ports:
        - containerPort: 9410
          name: terracotta-port
        - containerPort: 9430
          name: sync-port
        env:
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
        - name: dataroots-2-2
          mountPath: /data/dataroots
#        - name: backups
#          mountPath: /data/backups
        - name: config-volume
          mountPath: /configs
      volumes:
        - name: config-volume
          configMap:
            name: tc-configs
        - name: dataroots-2-2
          persistentVolumeClaim:
            claimName: dataroots-2-2
#        - name: backups
#          persistentVolumeClaim:
#            claimName: backups-volume-claim