{{- $root := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "terracotta.fullname" . }}-configuration
  labels:
    app: {{ template "terracotta.name" . }}
    chart: {{ template "terracotta.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  tc-config.properties: |
    #
    # Copyright Terracotta, Inc.
    #
    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #
    #     http://www.apache.org/licenses/LICENSE-2.0
    #
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    #


    # The name of the cluster the node will be part of
    cluster-name=tc-cluster
    failover-priority=availability
    #client-lease-duration=150s
    #client-reconnect-window=120s
    offheap-resources={{- range .Values.offheaps }}{{ .name }}:{{ .size }}{{ .unit }},{{- end}}
    {{ range $i :=  until (int .Values.replicaCount) }}
    stripe.1.node.{{ add $i 1 }}.name={{ template "terracotta.fullname" $root}}-{{ $i }}
    stripe.1.node.{{ add $i 1 }}.hostname={{ template "terracotta.fullname" $root}}-{{ $i }}.{{ template "terracotta.fullname" $root}}
    stripe.1.node.{{ add $i 1 }}.metadata-dir=/data/dataroots/metadata
    stripe.1.node.{{ add $i 1 }}.data-dirs=DATA_RESOURCE1:/data/dataroots/DATA_RESOURCE1,DATA_RESOURCE2:/data/dataroots/DATA_RESOURCE2
    stripe.1.node.{{ add $i 1 }}.log-dir=%H/terracotta/default-node1/logs
    stripe.1.node.{{ add $i 1 }}.backup-dir=/data/backups/
    {{ end }}