apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-tmc"
  labels:
    app: "{{ .Release.Name }}-tmc"
    chart: {{ template "terracotta.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-tmc"
      release: "{{ .Release.Name }}"
  serviceName: "{{ .Release.Name }}-tmc"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-tmc"
        release: "{{ .Release.Name }}"
    spec:
            {{- if .Values.affinity }}
      affinity:
            {{ toYaml .Values.affinity | indent 8 }}
            {{- end }}
      nodeSelector:
        kubernetes.io/hostname: tc-bigmemory-14
      containers:
        - name: "{{ .Release.Name }}-tmc"
          image: {{ .Values.tmcImage.repository }}:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: TMS_OFFHEAPSIZEMB
              value: "8192"
            - name: ACCEPT_EULA
              value: "Y"
            - name: TMS_AUTOCONNECT
              value: "true"
            - name: TMS_DEFAULTURL
              value: "terracotta://{{ template "terracotta.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
          ports:
            - name: tmc-port
              containerPort: 9480
          resources:
            limits:
              memory: "16Gi"
            requests:
              memory: "4Gi"
        - name: readiness
          image: "{{ .Values.clusterToolImage.repository }}:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.pullPolicy | quote }}
          command: ["sh", "-c", "while true; do sleep 86400; done"]
          readinessProbe:
            exec:
              command: ["bash", "-c", "bin/cluster-tool.sh -t 10000 status -n {{ template "terracotta.fullname" . }} -s {{ template "terracotta.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"]
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            # 10,000 as failure threshold gives around 41 hours of time to load from FRS and start terracotta successfully.
            failureThreshold: 10000
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}