apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-tmc"
  labels:
    app: "{{ .Release.Name }}-tmc"
    chart: {{ template "terracotta.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-tmc"
      release: "{{ .Release.Name }}"
  serviceName: "{{ .Release.Name }}-tmc"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-tmc"
        release: "{{ .Release.Name }}"
    spec:
            {{- if .Values.affinity }}
      affinity:
            {{ toYaml .Values.affinity | indent 8 }}
            {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      initContainers:
        - name: readiness
          image: "{{ .Values.registry }}/{{ .Values.clusterToolImage.name }}:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.pullPolicy | quote }}
          command: ["bin/cluster-tool.sh"]
          args: ["status", "-connect-to", "{{ template "terracotta.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"]
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

      containers:
        - name: "{{ .Release.Name }}-tmc"
          image: {{ .Values.registry }}/{{ .Values.tmcImage.name }}:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: TMS_OFFHEAPSIZEMB
              value: "8192"
            - name: ACCEPT_EULA
              value: "Y"
            - name: TMS_AUTOCONNECT
              value: "true"
            - name: TMS_DEFAULTURL
              value: "terracotta://{{ template "terracotta.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
          ports:
            - name: tmc-port
              containerPort: 9480
          resources:
            limits:
              memory: "16Gi"
            requests:
              memory: "4Gi"
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}